export const CharacterPhotoUrls: Record<string, string> = {
  "Mario": "https://www.smashbros.com/assets_v2/img/fighter/mario/main.png",
  "Donkey Kong": "https://www.smashbros.com/assets_v2/img/fighter/donkey_kong/main.png",
  "Link": "https://www.smashbros.com/assets_v2/img/fighter/link/main.png",
  "Samus & Dark Samus": "https://www.smashbros.com/assets_v2/img/fighter/samus/main.png",
  "Yoshi": "https://www.smashbros.com/assets_v2/img/fighter/yoshi/main.png",
  "Kirby": "https://www.smashbros.com/assets_v2/img/fighter/kirby/main.png",
  "Fox": "https://www.smashbros.com/assets_v2/img/fighter/fox/main.png",
  "Pikachu": "https://www.smashbros.com/assets_v2/img/fighter/pikachu/main.png",
  "Luigi": "https://www.smashbros.com/assets_v2/img/fighter/luigi/main.png",
  "Ness": "https://www.smashbros.com/assets_v2/img/fighter/ness/main.png",
  "Captain Falcon": "https://www.smashbros.com/assets_v2/img/fighter/captain_falcon/main.png",
  "Jigglypuff": "https://www.smashbros.com/assets_v2/img/fighter/jigglypuff/main.png",
  "Peach & Daisy": "https://www.smashbros.com/assets_v2/img/fighter/peach/main.png",
  "Bowser": "https://www.smashbros.com/assets_v2/img/fighter/bowser/main.png",
  "Ice Climbers": "https://www.smashbros.com/assets_v2/img/fighter/ice_climbers/main.png",
  "Sheik": "https://www.smashbros.com/assets_v2/img/fighter/sheik/main.png",
  "Zelda": "https://www.smashbros.com/assets_v2/img/fighter/zelda/main.png",
  "Dr Mario": "https://www.smashbros.com/assets_v2/img/fighter/dr_mario/main.png",
  "Pichu": "https://www.smashbros.com/assets_v2/img/fighter/pichu/main.png",
  "Falco": "https://www.smashbros.com/assets_v2/img/fighter/falco/main.png",
  "Marth": "https://www.smashbros.com/assets_v2/img/fighter/marth/main.png",
  "Lucina": "https://www.smashbros.com/assets_v2/img/fighter/lucina/main.png",
  "Young Link": "https://www.smashbros.com/assets_v2/img/fighter/young_link/main.png",
  "Ganondorf": "https://www.smashbros.com/assets_v2/img/fighter/ganondorf/main.png",
  "Mewtwo": "https://www.smashbros.com/assets_v2/img/fighter/mewtwo/main.png",
  "Roy": "https://www.smashbros.com/assets_v2/img/fighter/roy/main.png",
  "Chrom": "https://www.smashbros.com/assets_v2/img/fighter/chrom/main.png",
  "Mr Game & Watch": "https://www.smashbros.com/assets_v2/img/fighter/mr_game_and_watch/main.png",
  "Meta Knight": "https://www.smashbros.com/assets_v2/img/fighter/meta_knight/main.png",
  "Pit & Dark Pit": "https://www.smashbros.com/assets_v2/img/fighter/pit/main.png",
  "Zero Suit Samus": "https://www.smashbros.com/assets_v2/img/fighter/zero_suit_samus/main.png",
  "Wario": "https://www.smashbros.com/assets_v2/img/fighter/wario/main.png",
  "Snake": "https://www.smashbros.com/assets_v2/img/fighter/snake/main.png",
  "Ike": "https://www.smashbros.com/assets_v2/img/fighter/ike/main.png",
  "Pokemon Trainer": "https://www.smashbros.com/assets_v2/img/fighter/pokemon_trainer/main.png",
  "Diddy Kong": "https://www.smashbros.com/assets_v2/img/fighter/diddy_kong/main.png",
  "Lucas": "https://www.smashbros.com/assets_v2/img/fighter/lucas/main.png",
  "Sonic": "https://www.smashbros.com/assets_v2/img/fighter/sonic/main.png",
  "King Dedede": "https://www.smashbros.com/assets_v2/img/fighter/king_dedede/main.png",
  "Olimar": "https://www.smashbros.com/assets_v2/img/fighter/olimar/main.png",
  "Lucario": "https://www.smashbros.com/assets_v2/img/fighter/lucario/main.png",
  "ROB": "https://www.smashbros.com/assets_v2/img/fighter/rob/main.png",
  "Toon Link": "https://www.smashbros.com/assets_v2/img/fighter/toon_link/main.png",
  "Wolf": "https://www.smashbros.com/assets_v2/img/fighter/wolf/main.png",
  "Villager": "https://www.smashbros.com/assets_v2/img/fighter/villager/main.png",
  "Mega Man": "https://www.smashbros.com/assets_v2/img/fighter/mega_man/main.png",
  "Wii Fit Trainer": "https://www.smashbros.com/assets_v2/img/fighter/wii_fit_trainer/main.png",
  "Rosalina & Luma": "https://www.smashbros.com/assets_v2/img/fighter/rosalina_and_luma/main.png",
  "Little Mac": "https://www.smashbros.com/assets_v2/img/fighter/little_mac/main.png",
  "Greninja": "https://www.smashbros.com/assets_v2/img/fighter/greninja/main.png",
  "Palutena": "https://www.smashbros.com/assets_v2/img/fighter/palutena/main.png",
  "Pac-Man": "https://www.smashbros.com/assets_v2/img/fighter/pac_man/main.png",
  "Robin": "https://www.smashbros.com/assets_v2/img/fighter/robin/main.png",
  "Shulk": "https://www.smashbros.com/assets_v2/img/fighter/shulk/main.png",
  "Bowser Jr": "https://www.smashbros.com/assets_v2/img/fighter/bowser_jr/main.png",
  "Duck Hunt": "https://www.smashbros.com/assets_v2/img/fighter/duck_hunt/main.png",
  "Ryu": "https://www.smashbros.com/assets_v2/img/fighter/ryu/main.png",
  "Ken": "https://www.smashbros.com/assets_v2/img/fighter/ken/main.png",
  "Cloud": "https://www.smashbros.com/assets_v2/img/fighter/cloud/main.png",
  "Corrin": "https://www.smashbros.com/assets_v2/img/fighter/corrin/main.png",
  "Bayonetta": "https://www.smashbros.com/assets_v2/img/fighter/bayonetta/main.png",
  "Inkling": "https://www.smashbros.com/assets_v2/img/fighter/inkling/main.png",
  "Ridley": "https://www.smashbros.com/assets_v2/img/fighter/ridley/main.png",
  "Simon & Richter": "https://www.smashbros.com/assets_v2/img/fighter/simon/main.png",
  "King K Rool": "https://www.smashbros.com/assets_v2/img/fighter/king_k_rool/main.png",
  "Isabelle": "https://www.smashbros.com/assets_v2/img/fighter/isabelle/main.png",
  "Incineroar": "https://www.smashbros.com/assets_v2/img/fighter/incineroar/main.png",
  "Piranha Plant": "https://www.smashbros.com/assets_v2/img/fighter/piranha_plant/main.png",
  "Joker": "https://www.smashbros.com/assets_v2/img/fighter/joker/main.png",
  "Hero": "https://ssb.wiki.gallery/images/thumb/0/07/Hero_SSBU.png/500px-Hero_SSBU.png",
  "Banjo & Kazooie": "https://www.smashbros.com/assets_v2/img/fighter/banjo_and_kazooie/main.png",
  "Terry": "https://www.smashbros.com/assets_v2/img/fighter/terry/main.png",
  "Byleth": "https://www.smashbros.com/assets_v2/img/fighter/byleth/main.png",
  "Min Min": "https://www.smashbros.com/assets_v2/img/fighter/minmin/main.png",
  "Steve": "https://www.smashbros.com/assets_v2/img/fighter/steve/main.png",
  "Sephiroth": "https://www.smashbros.com/assets_v2/img/fighter/sephiroth/main.png",
  "Pyra & Mythra": "https://www.smashbros.com/assets_v2/img/fighter/pyra/main.png",
  "Kazuya": "https://www.smashbros.com/assets_v2/img/fighter/kazuya/main.png",
  "Sora": "https://www.smashbros.com/assets_v2/img/fighter/sora/main.png",
  "Mii Brawler": "https://ssb.wiki.gallery/images/thumb/e/e4/Mii_Brawler_SSBU.png/500px-Mii_Brawler_SSBU.png",
  "Mii Swordfighter": "https://ssb.wiki.gallery/images/thumb/f/fa/Mii_Swordfighter_SSBU.png/500px-Mii_Swordfighter_SSBU.png",
  "Mii Gunner": "https://ssb.wiki.gallery/images/thumb/e/e5/Mii_Gunner_SSBU.png/500px-Mii_Gunner_SSBU.png"
};